server.port=8070

# Tu używamy localhost, bo baza jest wystawiona na port 3306 Twojego komputera
spring.datasource.url=jdbc:mysql://localhost:3306/club?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=mysql

# Komunikacja z drugim mikroserwisem (jeśli on też działa lokalnie na porcie 8080)
ms.player.service.url=http://localhost:8080/webapi