# Unikalny port dla tego serwisu (zgodnie z Twoim docker-compose)
server.port=8080

# Adres bazy danych (pamiętaj o localhost zamiast nazwy serwisu z dockera)
spring.datasource.url=jdbc:mysql://localhost:3306/club?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=mysql

# Dodatkowe ustawienia deweloperskie
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true